name: Train and Deploy Faces Model

on:
  push:
    branches: [ master ]  # Cambié 'main' por 'master'
  pull_request:
    branches: [ master ]  # Cambié 'main' por 'master'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: hello-world
      run: echo "hello world workflows …"
    
    - name: Show python version
      run: python --version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download dataset from Google Drive
      run: |
        # Descarga el archivo comprimido desde Google Drive
        gdown --id 1p-PuVCJJDDl_CCyRIN0WVw-DVSeyRiWB
        # Extrae el archivo comprimido
        tar -xzvf caras_fotos.tgz

    - name: Verify files are downloaded
      run: ls -la # Para verificar que las fotos están correctamente descargadas

    - name: Execute model training
      run: python faces_model.py
    
    - name: Show root directory
      run: ls -la

    - name: List directory
      run: ls -R

    - name: Show model directory
      run: ls -la faces-model/1/

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Download and run the Docker base image
      run: docker run -d --name serving_base tensorflow/serving

    - name: Copy model to the Docker image
      run: docker cp faces-model/1 serving_base:/models/${{ secrets.MODEL_NAME }}

    - name: Build the custom Docker image
      run: docker commit --change "ENV MODEL_NAME ${{ secrets.MODEL_NAME }}" serving_base ${{ secrets.DOCKER_USER }}/tensorflow-${{ secrets.MODEL_NAME }}:${{ github.sha }}

    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_USER }}/tensorflow-${{ secrets.MODEL_NAME }}:${{ github.sha }}
