name: Train and Deploy Faces Model

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Show python version
      run: python --version

    - name: Install gdown to download dataset
      run: pip install gdown

    - name: Download dataset from Google Drive
      run: |
        # Descargar el archivo comprimido desde Google Drive usando el ID del archivo
        gdown --id 1p-PuVCJJDDl_CCyRIN0WVw-DVSeyRiWB
        # Extraer el archivo comprimido
        tar -xzvf caras_fotos.tgz

    - name: Verify files are downloaded
      run: ls -la # Para verificar que las fotos están correctamente descargadas

    - name: Execute model training
      run: |
        # Ejecutar el script de entrenamiento con las imágenes descargadas
        python faces_model.py
    
    - name: Show model directory
      run: ls -la faces-model/1/
